# Generated by Django 4.2.10 on 2024-02-15 20:19

from django.db import migrations
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0003_product_description_product_image_store_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, max_length=500, null=True, populate_from='name', unique=True),
        ),
    ]
